annotator/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('admin/', admin.site.urls),
    # path('annotator/', include('annotator_app.urls')),
    path('', include('data_provider.urls')),
    
    #path('', RedirectView.as_view(url='/', permanent=True)) 
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

annotator_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('informed_consent/', views.informed_consent, name='informed_consent'),
    path('upload_strava_workout/<prolific_id>', views.upload_strava_workout, name='upload_strava_workout'),
    path('download_strava_workout/<prolific_id>', views.download_strava_workout, name='download_strava_workout'),
    path('annotate_strava_workout/<prolific_id>', views.annotate_strava_workout, name='annotate_strava_workout'),
    path('upload_strava_overview/<prolific_id>', views.upload_strava_overview, name='upload_strava_overview'),
    path('download_strava_overview/<prolific_id>', views.download_strava_overview, name='download_strava_overview'),
    path('annotate_strava_overview/<prolific_id>', views.annotate_strava_overview, name='annotate_strava_overview'),
    path('thanks/', views.thanks, name='thanks'),
    path('leave/', views.leave, name='leave'),
]

annotator_app/models.py
from dcd.bucket.thing import Thing

class Bucket:

    __instance = None
    @staticmethod 
    def getInstance():
      """ Static access method. """
      if Bucket.__instance == None:
         Bucket.__instance = Bucket()
      return Bucket.__instance

    def __init__(self):
        self.thing = Thing()

        self.workout_screenshot_property = self.thing.find_or_create_property(
                "Strava Workout Screenshot", "IMAGE_PNG")

        self.overview_screenshot_property = self.thing.find_or_create_property(
                "Strava Overview Screenshot", "IMAGE_PNG")

        self.prolific_id_property = self.thing.find_or_create_property(
                "Prolific ID", "TEXT")

        self.workout_annotations_property = self.thing.find_or_create_property(
                "Strava Workout Annotations", "STRAVA_ANNOTATIONS")

        self.overview_annotations_property = self.thing.find_or_create_property(
                "Strava Overview Annotations", "STRAVA_ANNOTATIONS")

        self.workout_annotation_metrics_property = self.thing.find_or_create_property(
                "Strava Workout Annotation Metrics", "STRAVA_WORKOUT_ANNOTATION_METRICS")

    def upload_workout_screenshot(self, ts, file_name):
        values = (100,100)
        self.workout_screenshot_property.update_values(values, ts, file_name=file_name)

    def upload_overview_screenshot(self, ts, file_name):
        values = (100,100)
        self.overview_screenshot_property.update_values(values, ts, file_name=file_name)

    def download_workout_screenshot(self, ts):
        return self.workout_screenshot_property.read_media('image-png', ts)

    def download_overview_screenshot(self, ts):
        return self.overview_screenshot_property.read_media('image-png', ts)

    def save_workout_annotations(self, values, ts):
        self.workout_annotations_property.update_values(values=values, time_ms=ts)

    def save_overview_annotations(self, values, ts):
        self.overview_annotations_property.update_values(values=values, time_ms=ts)
    
    def save_workout_annotation_metrics(self, values, ts):
        self.workout_annotation_metrics_property.update_values(values=values, time_ms=ts)
    
    def save_prolific_id(self, prolific_id, ts):
        values = (prolific_id,)
        self.prolific_id_property.update_values(values=values, time_ms=ts)

annotator_app/forms.py
from django import forms

class ConsentForm(forms.Form):
    consent = forms.CheckboxInput()
    prolific_id = forms.TextInput()

class UploadWorkoutForm(forms.Form):
    screenshot_strava_workout = forms.FileField()

class UploadOverviewForm(forms.Form):
    screenshot_strava_overview = forms.FileField()

class AnnotateWorkoutForm(forms.Form):
    moving_time_min = forms.NumberInput()
    moving_time_sec = forms.NumberInput()
    distance = forms.NumberInput()
    pace = forms.NumberInput()
    time1 = forms.NumberInput()
    calories = forms.NumberInput()
    
    question1 = forms.Textarea()
    question2 = forms.Textarea()
    question3 = forms.Textarea()
    question4 = forms.Textarea()
    question5 = forms.Textarea()

class AnnotateOverviewForm(forms.Form):
    question1 = forms.Textarea()
    question2 = forms.Textarea()
    question3 = forms.Textarea()
    question4 = forms.Textarea()
    question5 = forms.Textarea()

annotator_app/views.py
from django.http.response import HttpResponse
from django.template.context_processors import csrf
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from annotator_app.forms import AnnotateWorkoutForm, AnnotateOverviewForm, ConsentForm, UploadWorkoutForm, UploadOverviewForm
import time
from datetime import datetime
import os


from annotator_app.models import Bucket

id_ts_map = {

}

def index(request):
    """View function for home page of site."""
    context = {}
    if "PROLIFIC_ID" in request.GET:
        context["prolific_id"] = request.GET['PROLIFIC_ID']   
    return render(request, 'index.html', context=context)
    
@csrf_exempt
def informed_consent(request):
    prolific_id = None
    if "PROLIFIC_ID" in request.GET:
        prolific_id = request.GET['PROLIFIC_ID']
    if request.method == 'POST':
        form = ConsentForm(request.POST)
        if form.is_valid():
            ts = int(time.time()) * 1000
            id_ts_map[prolific_id] = ts
            Bucket.getInstance().save_prolific_id(prolific_id, ts)
            return HttpResponseRedirect('/annotator/upload_strava_workout/' + prolific_id)
    else:
        form = ConsentForm()
    context = {
        "prolific_id": prolific_id,
        "form": form
    }
    return render(request, 'informed_consent.html', context=context)

@csrf_exempt
def upload_strava_workout(request, prolific_id):
    if request.method == 'POST':
        form = UploadWorkoutForm(request.POST, request.FILES)
        if form.is_valid():
            handle_workout_file(request.FILES['screenshot_strava_workout'], prolific_id)
            return HttpResponseRedirect('/annotator/annotate_strava_workout/' + prolific_id)
    else:
        form = UploadWorkoutForm()
    return render(request, 'upload_strava_workout.html', {'form': form})

@csrf_exempt
def handle_workout_file(f, id):
    file_name = f'./data/{id}-{id_ts_map[id]}-workout.png'
    with open(file_name, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)
    # Send file to Bucket
    Bucket.getInstance().upload_workout_screenshot(int(id_ts_map[id]), file_name)
    # Then we delete the local file
    os.remove(file_name)

@csrf_exempt
def annotate_strava_workout(request, prolific_id):
    if request.method == 'POST':
        form = AnnotateWorkoutForm(request.POST)
        if form.is_valid():
            calories = 0
            moving_time = int(request.POST['moving_time_minute'])*60 + int(request.POST['moving_time_second'])
            distance = float(request.POST['distance'])
            pace = int(request.POST['pace_minute'])*60 + int(request.POST['pace_second'])
            
            datestr=request.POST['date']
            time_hour=int(request.POST['run_time_hour'])
            time_minute=int(request.POST['run_time_minute'])
            timestr= datestr +'-'+ str(time_hour)+'-'+str(time_minute)
            t = datetime.strptime(timestr,'%Y-%m-%d-%H-%M')
            time1 = time.mktime(t.timetuple())
            

            # Save annotation metrics to bucket
            values_metrics = (moving_time, distance, pace, time1, calories)
            Bucket.getInstance().save_workout_annotation_metrics(values_metrics, int(id_ts_map[prolific_id]))

            q1 = request.POST['question1']
            q2 = request.POST['question2']
            q3 = request.POST['question3']
            q4 = request.POST['question4']
            q5 = request.POST['question5']
            # Save annotations to bucket
            values_questions = (q1, q2, q3, q4, q5)
            Bucket.getInstance().save_workout_annotations(values_questions, int(id_ts_map[prolific_id]))
            return HttpResponseRedirect('/annotator/upload_strava_overview/' + prolific_id)
    else:
        form = AnnotateWorkoutForm()

    return render(request, 'annotate_strava_workout.html', {'form': form, 'prolific_id': prolific_id})

@csrf_exempt
def download_strava_workout(request, prolific_id):
    if (id_ts_map[prolific_id] is not None):
        # Download image from bucket
        file_content = Bucket.getInstance().download_workout_screenshot(int(id_ts_map[prolific_id]))
        return HttpResponse(file_content, content_type='image/png')

@csrf_exempt
def upload_strava_overview(request, prolific_id):
    if request.method == 'POST':
        form = UploadOverviewForm(request.POST, request.FILES)
        if form.is_valid():
            handle_overview_file(request.FILES['screenshot_strava_overview'], prolific_id)
            return HttpResponseRedirect('/annotator/annotate_strava_overview/' + prolific_id)
    else:
        form = UploadOverviewForm()
    return render(request, 'upload_strava_overview.html', {'form': form})

@csrf_exempt
def handle_overview_file(f, id):
    file_name = f'./data/{id}-{id_ts_map[id]}-overview.png'
    with open(file_name, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)
    # Send file to Bucket
    Bucket.getInstance().upload_overview_screenshot(int(id_ts_map[id]), file_name)
    # Then we delete the local file
    os.remove(file_name)

@csrf_exempt
def annotate_strava_overview(request, prolific_id):
    if request.method == 'POST':
        form = AnnotateOverviewForm(request.POST)
        if form.is_valid():
            q1 = request.POST['question1']
            q2 = request.POST['question2']
            q3 = request.POST['question3']
            q4 = request.POST['question4']
            q5 = request.POST['question5']
            # Save annotations to bucket
            values_questions = (q1, q2, q3, q4, q5)
            Bucket.getInstance().save_overview_annotations(values_questions, int(id_ts_map[prolific_id]))
            return HttpResponseRedirect('/annotator/thanks')
    else:
        form = AnnotateOverviewForm()

    return render(request, 'annotate_strava_overview.html', {'form': form, 'prolific_id': prolific_id})

@csrf_exempt
def download_strava_overview(request, prolific_id):
    if (id_ts_map[prolific_id] is not None):
        # Download image from bucket
        file_content = Bucket.getInstance().download_overview_screenshot(int(id_ts_map[prolific_id]))
        return HttpResponse(file_content, content_type='image/png')

@csrf_exempt
def thanks(request):
    context = {}
    return render(request, 'thanks.html', context=context)

@csrf_exempt
def leave(request):
    context = {}
    return render(request, 'leave.html', context=context)

annotator_app/templates/annotate_strava_overview.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html style="font-size: 16px;">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="We partner with the world&amp;apos;s leading universities">
    <meta name="description" content="">
    <meta name="page_type" content="np-template-header-footer-from-plugin">
    <title>annotate training calendar</title>
    <link rel="stylesheet" href="{% static 'css/nicepage.css' %}" media="screen">
<link rel="stylesheet" href="{% static 'css/annotate-training-calendar.css' %}" media="screen">
    <script class="u-script" type="text/javascript" src="{% static 'js/jquery-1.9.1.min.js' %}" defer=""></script>
    <script class="u-script" type="text/javascript" src="{% static 'js/nicepage.js' %}" defer=""></script>
    <meta name="generator" content="Nicepage 4.3.1, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i">
    
    
    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": ""
}</script>
    <meta name="theme-color" content="#478ac9">
    <meta property="og:title" content="annotate training calendar">
    <meta property="og:type" content="website">
  </head>
  <body class="u-body">
    <section class="skrollable u-align-center u-clearfix u-section-1" id="carousel_23bf">
      <div class="u-clearfix u-sheet u-sheet-1">
        <h2 class="u-text u-text-1" spellcheck="false">Please annotate your traning calendar</h2>
        <div class="u-clearfix u-expanded-width u-layout-wrap u-layout-wrap-1">
          <div class="u-layout">
            <div class="u-layout-row">
              <div class="u-container-style u-layout-cell u-size-60 u-white u-layout-cell-1">
                <div class="u-container-layout u-container-layout-1">
                  <div style="text-align: center;">
                    <img style="width: 75%;" src="/annotator/download_strava_overview/{{ prolific_id }}" >
                    <p class="u-text u-text-2" spellcheck="false"> Your traning calendar</p>
                </div>
                 
                 
                  <div class="u-container-style u-group u-palette-2-base u-shape-rectangle u-group-1">
                    <div class="u-container-layout u-valign-middle u-container-layout-2">
                      <p class="u-text u-text-body-alt-color u-text-3" spellcheck="false">Annotate your traning calendar</p>
                    </div>
                  </div>
                  <p class="u-text u-text-4" spellcheck="false">Please read your uploaded training calendar carefully. Then, try to reflect on your past training experiences, and answer the questions below.</p>
                  <p class="u-text u-text-4" spellcheck="false">                   </p>
                  <div class="u-expanded-width u-form u-form-1">
                    <!--form action="" method="post"  class="u-clearfix u-form-spacing-10 u-form-vertical u-inner-form" style="padding: 10px;"-->
                    <form action="" method="post"  style="padding: 10px;">
                        {% csrf_token %}
                      
                      <div class="u-form-group u-form-message">
                        <label for="id_question1" class="u-label">1.Reflecting on the activities in the calendar, what time of the day and what date of the week do you prefer to exercise, why?</label>
                        <textarea placeholder="" rows="2" cols="50" id="id_question1" name="question1" class="u-border-1 u-border-grey-30 u-input u-input-rectangle u-white" required=""></textarea>
                      </div>
                      <p class="u-text u-text-4" spellcheck="false">                   </p>
                      <div class="u-form-group u-form-textarea u-form-group-2">
                        <label for="id_question2" class="u-label">2.Which training record in the training calendar do you like best, and why?</label>
                        <textarea rows="2" cols="50" id="id_question2" name="question2" class="u-border-1 u-border-grey-30 u-input u-input-rectangle u-white" required=""></textarea>
                      </div>
                      <p class="u-text u-text-4" spellcheck="false">                   </p>
                      <div class="u-form-group u-form-textarea u-form-group-3">
                        <label for="id_question3" class="u-label">3. What are you busy with during the gap where you did not exercise so much? What makes you feel run less?  </label>
                        <textarea rows="2" cols="50" id="id_question3" name="question3" class="u-border-1 u-border-grey-30 u-input u-input-rectangle u-white" required=""></textarea>
                      </div>
                      <p class="u-text u-text-4" spellcheck="false">                   </p>
                      <div class="u-form-group u-form-textarea u-form-group-4">
                        <label for="id_question4" class="u-label">4.In this month, what factor or event in your daily life motivates you to exercise/run?
                        <textarea rows="2" cols="50" id="id_question4" name="question4" class="u-border-1 u-border-grey-30 u-input u-input-rectangle u-white" required=""></textarea>
                      </div>
                      <p class="u-text u-text-4" spellcheck="false">                   </p>
                      <div class="u-form-group u-form-textarea u-form-group-5">
                        <label for="id_question5" class="u-label">5.Are you satisfied with your training frequency of this month? What are you satisfied/unsatisfied with?</label>
                        <textarea rows="2" cols="50" id="id_question5" name="question5" class="u-border-1 u-border-grey-30 u-input u-input-rectangle u-white" required=""></textarea>
                      </div>

                      <div class="u-align-center u-form-group u-form-submit">
                        <input type="submit" value="submit!" class="u-border-none u-btn u-btn-submit u-button-style u-palette-2-base u-btn-1">
                      </div>

                     
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    
    
  </body>
</html>





<!--form action="" method="post">
    {% csrf_token %}
    <p>Annotations</p>
    <label for="id_question1">Question 1: ...</label><br>
    <textarea id="id_question1" name="question1" required></textarea><br>
    <label for="id_question2">Question 2: ...</label><br>
    <textarea id="id_question2" name="question2" required></textarea><br>
    <label for="id_question3">Question 3: ...</label><br>
    <textarea id="id_question3" name="question3" required></textarea><br>
    <label for="id_question4">Question 4: ...</label><br>
    <textarea id="id_question4" name="question4" required></textarea><br>
    <label for="id_question5">Question 5: ...</label><br>
    <textarea id="id_question5" name="question5" required></textarea><br>
    <hr>
    <input type="submit" value="Next">
</form-->

{% endblock %}

annotator_app/templates/base_generic_notusing.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block header %}<title>Annotator</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>





<body>
    <div class="container-fluid">
        <header class="row">
            <div class="col-sm-12">
                <h1>Annotator</h1>
            </div>
        </header>
        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                <!-- <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="">All books</a></li>
          <li><a href="">All authors</a></li>
        </ul> -->
                {% endblock %}
            </div>
            <main class="col-sm-10 ">
                {% block content %}{% endblock %}
            </main>
        </div>
    </div>
</body>

</html>

annotator_app/templates/informed_consent.html
{% block content %}

<!DOCTYPE html>
<html style="font-size: 16px;">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="We partner with the world&amp;apos;s leading universities">
    <meta name="description" content="">
    <meta name="page_type" content="np-template-header-footer-from-plugin">

    {% load static %}
    <title>check license</title>
    <link rel="stylesheet" href="{% static 'css/nicepage.css' %}" media="screen">
<link rel="stylesheet" href="{% static 'css/check-license.css' %}" media="screen">
    <script class="u-script" type="text/javascript" src="{% static 'js/jquery.js' %}" defer=""></script>
    <script class="u-script" type="text/javascript" src="{% static 'js/nicepage.js' %}" defer=""></script>
    <meta name="generator" content="Nicepage 4.3.3, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i">
    
    
    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": ""
    
}</script>
    <meta name="theme-color" content="#478ac9">
    <meta property="og:title" content="check license">
    <meta property="og:type" content="website">
  </head>
  <body class="u-body">
    <section class="u-align-center u-clearfix u-section-1" id="carousel_23bf">
      <div class="u-clearfix u-sheet u-sheet-1">
        <h2 class="u-text u-text-1" spellcheck="false">Please check the informed consent</h2>
        <div class="u-clearfix u-expanded-width u-layout-wrap u-layout-wrap-1">
          <div class="u-layout">
            <div class="u-layout-row">
              <div class="u-container-style u-layout-cell u-size-60 u-white u-layout-cell-1">
                <div class="u-container-layout u-container-layout-1">
                  <div class="u-container-style u-group u-palette-2-base u-shape-rectangle u-group-1">
                    <div class="u-container-layout u-container-layout-2">
                      <p class="u-text u-text-body-alt-color u-text-2" spellcheck="false">Are you the one we are looking for?</p>
                    </div>
                  </div>
                  <p class="u-align-justify u-text u-text-3" spellcheck="false">You are being invited to scientific research around Strava running experiences.&nbsp;Your participation is completely voluntary, and you can withdraw at any time.
To participate in this survey, we expect you are:<br>1. at least 18 years old<br>2. <span style="font-weight: 700;">a Strava user who has 5 running records in recent 2 months</span>
                  </p>
                  <div class="u-container-style u-group u-palette-2-base u-shape-rectangle u-group-2">
                    <div class="u-container-layout u-valign-top u-container-layout-3">
                      <p class="u-text u-text-4" spellcheck="false">What task will you do?</p>
                    </div>
                  </div>
                  <p class="u-align-justify u-text u-text-5" spellcheck="false">You will be invited to do the following tasks:
                  </p>
                  <ul class="u-align-justify u-text u-text-6" spellcheck="false">
                    <li>Upload screenshots of the Strava activity records,including running route
map (<span style="font-weight: 700;">in recent two-months</span>) and training calendar (<span style="font-weight: 700;">in recent two-months and at least 3 activity records</span>). 
                    </li>
                    <li>Then, please reflect on the uploaded screenshots and answer questions around your running experiences in text format.​</li>
                  </ul>
                  <img class="u-image u-image-default u-image-1" src="{% static 'img/informed_consent_route_map.png' %}" alt="" data-image-width="1188" data-image-height="864">
                  <img class="u-image u-image-default u-image-2" src="{% static 'img/informed_consent_training_calendar.png' %}" alt="" data-image-width="1774" data-image-height="1080">
                  <p class="u-align-center u-text u-text-7" spellcheck="false">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Running route map&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ​&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;​&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Training calendar<br>
                  </p>
                  <p class="u-align-justify u-text u-text-8" spellcheck="false"> <span style="font-weight: 700;"> We cannot pay you if you do not meet those requriments even if you complete the whole tasks. </span> This study will be approved within
21 days. The total task will take you approximately 15 minutes maximum to complete.<br>
                  </p>
                  <div class="u-container-style u-group u-palette-2-base u-shape-rectangle u-group-3">
                    <div class="u-container-layout u-container-layout-4">
                      <p class="u-text u-text-body-alt-color u-text-9" spellcheck="false">What data will be collected?</p>
                    </div>
                  </div>
                  <p class="u-align-justify u-text u-text-10" spellcheck="false">We will collect the following data for research:&nbsp;<br>
                  </p>
                  <ul class="u-align-justify u-text u-text-11" spellcheck="false">
                    <li>Strava App screenshots:&nbsp;<span style="font-size: 1.125rem; color: #111111; background-color: #ffffff; font-family: 'Open Sans',sans-serif;">running route map&nbsp;</span>
                      <span style="font-size: 1.125rem; color: #111111; background-color: #ffffff; font-family: 'Open Sans',sans-serif;">and training calendar </span>
                    </li>
                    <li>Overall information about specific runs, including timestamps, moving time,
distance etc.</li>
                    <li>Annotations of running experience in text format&nbsp;<span style="font-size: 1.125rem; color: #111111; background-color: #ffffff; font-family: 'Open Sans',sans-serif;">(a list of questions around
running experiences will be provided for you to reflect upon collected screenshots)​</span>
                    </li>
                  </ul>
                  <div class="u-container-style u-group u-palette-2-base u-shape-rectangle u-group-4">
                    <div class="u-container-layout u-container-layout-5">
                      <p class="u-text u-text-body-alt-color u-text-12" spellcheck="false">How do we protect your data?</p>
                    </div>
                  </div>
                  <p class="u-align-justify u-text u-text-13" spellcheck="false">We believe there are no known risks associated with this research study. However, as
with any online related activity, the risk of a breach is always possible. 
<br>
                  </p>
                  <ul class="u-align-justify u-text u-text-14" spellcheck="false">
                    <li>&nbsp;We design this survey to be anonymous, where all identifying information is
removed and replaced with your Prolific ID.&nbsp;</li>
                    <li>&nbsp;We will provide clear and detailed instructions to take correct screenshots, and exclude your personal information.<span style="font-weight: 700;"> Please follow the instructions strictly.&nbsp;</span>
                    </li>
                    <li>If any identifying information is collected, we will delete it immediately before
storing.&nbsp;</li>
                    <li>&nbsp;We will store all data on a password-protected, encrypted computer and server,
and data will only be accessed by our research group members.<br>
                    </li>
                  </ul>
                  <div class="u-form u-form-1">
                    <form action="" method="post" class="u-clearfix u-form-custom-backend u-form-spacing-10 u-form-vertical u-inner-form"  style="padding: 10px;" >
                           {% csrf_token %}
                      <div class="u-form-checkbox u-form-group u-label-top u-form-group-1">
                        <input type="checkbox" id="id_consent" name="consent"  required="required">
                        <label for="id-consent" class="u-label">I meet the requirements</label>
                      </div>
                      <div class="u-align-left u-form-group u-form-submit">
                        <input type="submit" value="I agree, go to do tasks!" class="u-btn u-btn-submit u-button-style u-palette-2-base u-btn-1">
                      </div>
                    </form>
                  </div>
                  <a href="https://prolific.co" class="u-border-none u-btn u-button-style u-grey-40 u-hover-grey-40 u-btn-2">I don't agree, direct me to Prolific</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

<!--form action="" method="post">
    {% csrf_token %}
    <label for="id_consent">I agree</label>
    <input type="checkbox" id="id_consent" name="consent" required /> <br>
    <input type="submit" value="Agree and Start">
</form-->

{% endblock %}